# Generated by Django 3.0.8 on 2020-08-26 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200810_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='imagenes_productos/categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=240)),
                ('address', models.CharField(max_length=240)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('titulo_cortesia', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('fecha_contrato', models.DateField()),
                ('direccion', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('codigo_postal', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=120)),
                ('extension', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='imagenes_productos/empleados/')),
                ('notas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shippers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=120)),
                ('region', models.CharField(max_length=120)),
                ('postal_code', models.IntegerField()),
                ('country', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=129)),
                ('home_page', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='unidades_orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='unidades_stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingresarproductos',
            name='photo',
            field=models.ImageField(upload_to='imagenes_productos/products/'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateTimeField()),
                ('customers_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Customers')),
                ('employees_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Employees')),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.Orders')),
                ('products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.IngresarProductos')),
            ],
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='categories_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresarproductos',
            name='suppliers_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.Suppliers'),
            preserve_default=False,
        ),
    ]
