# Generated by Django 3.0.8 on 2020-08-28 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200828_0501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Order_details',
            new_name='Order_detail',
        ),
        migrations.RenameModel(
            old_name='Shippers',
            new_name='Shipper',
        ),
        migrations.RenameModel(
            old_name='Suppliers',
            new_name='Supplier',
        ),
    ]
