# Generated by Django 3.0.8 on 2020-08-28 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20200828_0506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngresarProductos',
            new_name='Product',
        ),
    ]
