# Generated by Django 3.0.8 on 2020-09-01 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20200828_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='name',
        ),
    ]
